/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magesft.crearartistas;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import magesft.sockets.Sockets;

/**
 *
 * @author Gonzalo
 */
public class CrearArtistas extends javax.swing.JFrame {
    JFrame jf;
    /**
     * Creates new form CrearArtistas
     */
    public CrearArtistas(JFrame jf) {
        this.jf=jf;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        l_fecha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Btnatras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(381, 310));
        setMinimumSize(new java.awt.Dimension(381, 310));
        setPreferredSize(new java.awt.Dimension(381, 310));
        getContentPane().setLayout(null);

        jLabel1.setText("Nuevos Artistas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(137, 27, 150, 14);

        jLabel2.setText("Nombre del grupo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 80, 140, 14);
        getContentPane().add(l_nombre);
        l_nombre.setBounds(189, 71, 145, 31);

        jLabel3.setText("Fecha de inicio:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(58, 128, 120, 14);
        getContentPane().add(l_fecha);
        l_fecha.setBounds(189, 120, 145, 30);

        jButton1.setText("Alta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(264, 226, 70, 23);

        Btnatras.setText("Atrás");
        Btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnatrasActionPerformed(evt);
            }
        });
        getContentPane().add(Btnatras);
        Btnatras.setBounds(10, 226, 100, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract-background-design.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-6, 0, 390, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            String nombre=l_nombre.getText();
            String fecha=l_fecha.getText();
            if(fecha.contains("/")){
                fecha=fecha.replace("/", "-");
            }
            Sockets so=new Sockets();
            ObjectInputStream in=so.getIn();
            ObjectOutputStream out=so.getOut();
            Socket s=so.getS();
            String [] campos={"Nombre","Fecha_inicio"};
            String [] insertar={nombre,fecha};
            System.out.println((String)in.readObject());
            out.writeObject(0);
            out.writeObject("autor");
            out.writeObject(campos);
            out.writeObject(insertar);
        } catch (IOException ex) {
            Logger.getLogger(CrearArtistas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearArtistas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnatrasActionPerformed
        jf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnatrasActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnatras;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField l_fecha;
    private javax.swing.JTextField l_nombre;
    // End of variables declaration//GEN-END:variables
}
