/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magesft2.servidor;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import magesft.buscarcanciones.BuscarCanciones;
import magesft.crearmusica.CrearMusica;
import magesft.crearusuario.CrearUsuario;
import magesft.eliminarusuario.EliminarUsuario;

/**
 *
 * @author ivan
 */
public class MenuServidor extends javax.swing.JFrame {
    JFrame jf;
    /**
     * Creates new form MenuServidor
     */
    public MenuServidor() {
        initComponents();
    }
    public MenuServidor(JFrame jf) {
        initComponents();
        this.jf=jf;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btncrearusuario = new javax.swing.JButton();
        BtnMusica = new javax.swing.JButton();
        BtnBuscarCanciones = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btncrearusuario.setText("Crear Usuario");
        Btncrearusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtncrearusuarioActionPerformed(evt);
            }
        });

        BtnMusica.setText("Crear Musica");
        BtnMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMusicaActionPerformed(evt);
            }
        });

        BtnBuscarCanciones.setText("Buscar Canciones");
        BtnBuscarCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarCancionesActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar Usuario");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btncrearusuario)
                    .addComponent(BtnBuscarCanciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnMusica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btncrearusuario)
                    .addComponent(BtnMusica))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBuscarCanciones)
                    .addComponent(BtnEliminar))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtncrearusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtncrearusuarioActionPerformed
        CrearUsuario c=new CrearUsuario(this);
        c.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BtncrearusuarioActionPerformed

    private void BtnMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMusicaActionPerformed
        CrearMusica c;
        try {
            c = new CrearMusica(this);
            c.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuServidor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuServidor.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_BtnMusicaActionPerformed

    private void BtnBuscarCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarCancionesActionPerformed
        BuscarCanciones c=new BuscarCanciones(this);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnBuscarCancionesActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        EliminarUsuario e=new EliminarUsuario(this);
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarCanciones;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnMusica;
    private javax.swing.JButton Btncrearusuario;
    // End of variables declaration//GEN-END:variables
}
