/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magesft2.servidor;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import magesft.buscarcanciones.BuscarCanciones;
import magesft.crearartistas.CrearArtistas;
import magesft.crearmusica.CancionesAlbum;
import magesft.crearmusica.CrearAlbum;
import magesft.crearmusica.CrearMusica;
import magesft2.eliminarcanciones.EliminarCanciones;
import magesft.eliminarusuario.EliminarUsuario;
import magesft2.crearusuario.CrearUsuario;
import magesft2.mensajes.Iniciosesiongmail;
import magesft2.serv_func.funcion;


/**
 *
 * @author ivan
 */
public class MenuServidor extends javax.swing.JFrame {
    JFrame jf;
    /**
     * Creates new form MenuServidor
     */
    public MenuServidor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public MenuServidor(JFrame jf) {
    
            initComponents();
            this.setLocationRelativeTo(null);
            this.jf=jf;
            
            
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btncrearusuario = new javax.swing.JButton();
        BtnMusica = new javax.swing.JButton();
        BtnBuscarCanciones = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BtnEliminarcancioens = new javax.swing.JButton();
        BtnCrearArtista = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(815, 350));
        setMinimumSize(new java.awt.Dimension(815, 350));
        setPreferredSize(new java.awt.Dimension(815, 350));
        getContentPane().setLayout(null);

        Btncrearusuario.setBackground(new java.awt.Color(51, 255, 255));
        Btncrearusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/006-sign.png"))); // NOI18N
        Btncrearusuario.setText("Crear Usuario");
        Btncrearusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtncrearusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Btncrearusuario);
        Btncrearusuario.setBounds(30, 150, 170, 33);

        BtnMusica.setBackground(new java.awt.Color(51, 255, 255));
        BtnMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/004-add-song.png"))); // NOI18N
        BtnMusica.setText("Crear Musica");
        BtnMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMusicaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMusica);
        BtnMusica.setBounds(230, 150, 170, 33);

        BtnBuscarCanciones.setBackground(new java.awt.Color(51, 255, 255));
        BtnBuscarCanciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/003-video-player.png"))); // NOI18N
        BtnBuscarCanciones.setText("Buscar Canciones");
        BtnBuscarCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarCancionesActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBuscarCanciones);
        BtnBuscarCanciones.setBounds(230, 230, 170, 33);

        BtnEliminar.setBackground(new java.awt.Color(51, 255, 255));
        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/003-delete.png"))); // NOI18N
        BtnEliminar.setText("Eliminar Usuario");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEliminar);
        BtnEliminar.setBounds(30, 190, 170, 33);

        jButton1.setBackground(new java.awt.Color(51, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/002-send.png"))); // NOI18N
        jButton1.setText("Enviar Mensajes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 280, 230, 33);

        BtnEliminarcancioens.setBackground(new java.awt.Color(51, 255, 255));
        BtnEliminarcancioens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/001-delete-song-interface-symbol.png"))); // NOI18N
        BtnEliminarcancioens.setText("Eliminar Canciones");
        BtnEliminarcancioens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarcancioensActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEliminarcancioens);
        BtnEliminarcancioens.setBounds(230, 190, 170, 33);

        BtnCrearArtista.setBackground(new java.awt.Color(51, 255, 255));
        BtnCrearArtista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/006-sign.png"))); // NOI18N
        BtnCrearArtista.setText("Crear Artistas");
        BtnCrearArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearArtistaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCrearArtista);
        BtnCrearArtista.setBounds(30, 230, 170, 33);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SoulMusic.JPG"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 40, 530, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconomage.JPG"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(550, 10, 240, 140);

        jButton2.setBackground(new java.awt.Color(51, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/004-add-song.png"))); // NOI18N
        jButton2.setText("Crear Album");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(570, 180, 210, 33);

        jButton3.setBackground(new java.awt.Color(51, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/001-mark.png"))); // NOI18N
        jButton3.setText("Añadir canciones a Album");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 280, 270, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract-background-design.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-16, -20, 830, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtncrearusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtncrearusuarioActionPerformed
        CrearUsuario c=new CrearUsuario(this,1);
        c.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BtncrearusuarioActionPerformed

    private void BtnMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMusicaActionPerformed
        CrearMusica c;
        try {
            c = new CrearMusica(this);
            c.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuServidor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuServidor.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_BtnMusicaActionPerformed

    private void BtnBuscarCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarCancionesActionPerformed
        BuscarCanciones c=new BuscarCanciones(this);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnBuscarCancionesActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        EliminarUsuario e=new EliminarUsuario(this);
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnEliminarcancioensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarcancioensActionPerformed
        EliminarCanciones e=new EliminarCanciones(this);
        e.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BtnEliminarcancioensActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Iniciosesiongmail m=new Iniciosesiongmail(this);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnCrearArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearArtistaActionPerformed
        CrearArtistas a=new CrearArtistas(this);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnCrearArtistaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CrearAlbum ca=new CrearAlbum(this);
        ca.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CancionesAlbum ca=new CancionesAlbum(this);
        ca.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuServidor().setVisible(true);
                funcion f=new funcion();
                f.start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarCanciones;
    private javax.swing.JButton BtnCrearArtista;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnEliminarcancioens;
    private javax.swing.JButton BtnMusica;
    private javax.swing.JButton Btncrearusuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
