/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magesft2.servidor;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import magesft.buscarcanciones.BuscarCanciones;
import magesft.crearartistas.CrearArtistas;
import magesft.crearmusica.CrearMusica;
import magesft2.eliminarcanciones.EliminarCanciones;
import magesft.eliminarusuario.EliminarUsuario;
import magesft2.crearusuario.CrearUsuario;
import magesft2.mensajes.Iniciosesiongmail;
import magesft2.serv_func.funcion;


/**
 *
 * @author ivan
 */
public class MenuServidor extends javax.swing.JFrame {
    JFrame jf;
    /**
     * Creates new form MenuServidor
     */
    public MenuServidor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public MenuServidor(JFrame jf) {
    
            initComponents();
            this.setLocationRelativeTo(null);
            this.jf=jf;
            
            
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btncrearusuario = new javax.swing.JButton();
        BtnMusica = new javax.swing.JButton();
        BtnBuscarCanciones = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BtnEliminarcancioens = new javax.swing.JButton();
        BtnCrearArtista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btncrearusuario.setText("Crear Usuario");
        Btncrearusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtncrearusuarioActionPerformed(evt);
            }
        });

        BtnMusica.setText("Crear Musica");
        BtnMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMusicaActionPerformed(evt);
            }
        });

        BtnBuscarCanciones.setText("Buscar Canciones");
        BtnBuscarCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarCancionesActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar Usuario");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        jButton1.setText("Enviar Mensajes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BtnEliminarcancioens.setText("Eliminar Canciones");
        BtnEliminarcancioens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarcancioensActionPerformed(evt);
            }
        });

        BtnCrearArtista.setText("Crear Artistas");
        BtnCrearArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearArtistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnCrearArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BtnBuscarCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnEliminarcancioens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btncrearusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnMusica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btncrearusuario)
                    .addComponent(BtnMusica))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBuscarCanciones)
                    .addComponent(BtnEliminar))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(BtnEliminarcancioens))
                .addGap(35, 35, 35)
                .addComponent(BtnCrearArtista)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtncrearusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtncrearusuarioActionPerformed
        CrearUsuario c=new CrearUsuario(this,1);
        c.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BtncrearusuarioActionPerformed

    private void BtnMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMusicaActionPerformed
        CrearMusica c;
        try {
            c = new CrearMusica(this);
            c.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuServidor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuServidor.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_BtnMusicaActionPerformed

    private void BtnBuscarCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarCancionesActionPerformed
        BuscarCanciones c=new BuscarCanciones(this);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnBuscarCancionesActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        EliminarUsuario e=new EliminarUsuario(this);
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnEliminarcancioensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarcancioensActionPerformed
        EliminarCanciones e=new EliminarCanciones(this);
        e.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BtnEliminarcancioensActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Iniciosesiongmail m=new Iniciosesiongmail(this);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnCrearArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearArtistaActionPerformed
        CrearArtistas a=new CrearArtistas(this);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnCrearArtistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuServidor().setVisible(true);
                funcion f=new funcion();
                f.start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarCanciones;
    private javax.swing.JButton BtnCrearArtista;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnEliminarcancioens;
    private javax.swing.JButton BtnMusica;
    private javax.swing.JButton Btncrearusuario;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
