/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magesft2.eliminarcanciones;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import magesft.clases.Musica;
import magesft.sockets.Sockets;
import magesft2.conectar.Conexion_BBDD;

/**
 *
 * @author Gonzalo
 */
public class EliminarCanciones extends javax.swing.JFrame {

    DefaultListModel<Musica> dfm;
    LinkedList<Musica> l_musica;
    int album_borrar;
    JFrame jf;

    /**
     * Creates new form EliminarCanciones
     */
    public EliminarCanciones(JFrame jf) {
        this.jf=jf;
        initComponents();
        try {
            this.setLocationRelativeTo(null);
            album_borrar = -1;
            dfm = new DefaultListModel<>();
            l_musica = new LinkedList<>();
            Sockets so = new Sockets();

            Socket s = so.getS();
            ObjectInputStream in = so.getIn();
            ObjectOutputStream out = so.getOut();

            System.out.println(in.readObject());
            String[] campos = {"Nombre"};
            String condicion = "";
            out.writeObject(1);
            out.writeObject("autor");
            out.writeObject(campos);
            out.writeObject(condicion);
            ArrayList<String[]> arr = (ArrayList<String[]>) in.readObject();

            for (int i = 0; i < arr.size(); i++) {
                c_artistas.addItem(((String[]) arr.get(i))[0]);
            }

            so = new Sockets();
            s = so.getS();
            in = so.getIn();
            out = so.getOut();

            System.out.println(in.readObject());
            String[] campos2 = {"ID", "Nombre_album"};
            out.writeObject(1);
            out.writeObject("album");
            out.writeObject(campos2);
            out.writeObject(condicion);
            arr = (ArrayList<String[]>) in.readObject();

            for (int i = 0; i < arr.size(); i++) {
                c_album.addItem(((String[]) arr.get(i))[0] + "-" + ((String[]) arr.get(i))[1]);
            }

        } catch (IOException ex) {
            Logger.getLogger(EliminarCanciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EliminarCanciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        c_artistas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        c_album = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        l_titulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_musica = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(687, 420));
        setMinimumSize(new java.awt.Dimension(687, 420));
        setPreferredSize(new java.awt.Dimension(687, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Buscar canciones:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(432, 26, 180, 17);

        c_artistas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        getContentPane().add(c_artistas);
        c_artistas.setBounds(101, 64, 119, 27);

        jLabel2.setText("Artista:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(22, 67, 70, 17);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 370, 100, 29);

        jLabel3.setText("Album:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(22, 119, 70, 17);

        c_album.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        getContentPane().add(c_album);
        c_album.setBounds(101, 116, 119, 27);

        jLabel4.setText("Titulo: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(22, 175, 60, 17);
        getContentPane().add(l_titulo);
        l_titulo.setBounds(101, 172, 119, 27);

        jScrollPane1.setViewportView(list_musica);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(338, 64, 310, 300);

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 370, 110, 29);

        jButton3.setText("Atrás");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 370, 90, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract-background-design.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-6, 0, 690, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        try {
            // TODO add your handling code here:
            l_musica = new LinkedList<>();
            dfm = new DefaultListModel<>();
            Sockets so = new Sockets();
            ArrayList<String[]> musica = new ArrayList<>();
            Conexion_BBDD c=new Conexion_BBDD();
            
            String artistas = (String) c_artistas.getSelectedItem();
            String album = (String) c_album.getSelectedItem();
            String nombre = l_titulo.getText();
            
            if (nombre.compareToIgnoreCase("") != 0) {
                
                String[] campos = {"Nombre_cancion", "Autor", "ID", "Duracion", "enlace", "Precio"};
                String condicion = " where Nombre_cancion='" + nombre + "'";
                
                
                ArrayList<String[]> arr = c.consulta("musica", campos, condicion);
                for (int i = 0; i < arr.size(); i++) {
                    musica.add(arr.get(i));
                }
                
            } else {
                if (artistas.compareToIgnoreCase("") != 0) {
                    
                    
                    String[] campos = {"Nombre_cancion", "Autor", "ID", "Duracion", "enlace", "Precio"};
                    String condicion = " where Autor='" + artistas + "'";
                    
                    ArrayList<String[]> arr = c.consulta("musica", campos, condicion);
                    for (int i = 0; i < arr.size(); i++) {
                        musica.add(arr.get(i));
                    }
                    
                } else {
                    if (album.compareToIgnoreCase("") != 0) {
                        
                        String[] campos = {"ID_Musica"};
                        album_borrar=Integer.parseInt(album.substring(0, album.indexOf("-")));
                        String condicion = " where ID_Album='" + String.valueOf(album_borrar) + "'";
                        
                        ArrayList<String[]> arr = c.consulta("linea_album", campos, condicion);
                        
                        String[] campos2 = {"Nombre_cancion", "Autor", "ID", "Duracion", "enlace", "Precio"};
                        for (int i = 0; i < arr.size(); i++) {
                            
                            condicion = " where ID='" + ((String[]) arr.get(i))[0] + "'";
                            
                            arr = c.consulta("musica", campos2, condicion);
                            musica.add(arr.get(0));
                        }
                        for (int i = 0; i < musica.size(); i++) {
                            System.out.println(((String[]) musica.get(i))[0]);
                        }
                        
                    
                } else {
                        JOptionPane.showMessageDialog(this, "Rellena alguno de los campos");
                        }
                
                }
       
            }
            for (int i = 0; i < musica.size(); i++) {
                String cancion = "";
                Musica m = new Musica(((String[]) musica.get(i))[0], ((String[]) musica.get(i))[1], ((String[]) musica.get(i))[2], ((String[]) musica.get(i))[3], ((String[]) musica.get(i))[4], ((String[]) musica.get(i))[5]);
                l_musica.add(m);
                dfm.add(i, m);
            }
            list_musica.setModel(dfm);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EliminarCanciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EliminarCanciones.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (album_borrar != -1) {
            try {
                
                String condicion = " ID_Album='" + String.valueOf(album_borrar) + "'";

                
                
                Conexion_BBDD c=new Conexion_BBDD();
                c.delete("linea_album", condicion);
                
                condicion = " ID='" + album_borrar + "'";

                c=new Conexion_BBDD();
                if(!c.delete("album", condicion)){
                    JOptionPane.showMessageDialog(this, "No se ha podido eliminar el album");
                }

                

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(EliminarCanciones.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(EliminarCanciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        for (int i = 0; i < l_musica.size(); i++) {
            try {
                
                String condicion = " ID='" + l_musica.get(i).getIden() + "'";
                
                Conexion_BBDD c=new Conexion_BBDD();
                c.delete("musica", condicion);
            }  catch (ClassNotFoundException ex) {
                Logger.getLogger(EliminarCanciones.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(EliminarCanciones.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
        EliminarCanciones el=new EliminarCanciones(this);
        el.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         jf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c_album;
    private javax.swing.JComboBox<String> c_artistas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField l_titulo;
    private javax.swing.JList<Musica> list_musica;
    // End of variables declaration//GEN-END:variables
}
