/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magesft.crearusuario;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import magesft.clases.Usuario;
import magesft.sockets.Sockets;
import magesft2.conectar.Conexion_BBDD;

/**
 *
 * @author ivan
 */
public class CrearUsuario extends javax.swing.JFrame {
int rol_padre;
    /**
     * Creates new form CrearUsuario
     */
    public CrearUsuario() {
        initComponents();
    }
    public CrearUsuario(final JFrame frame, final int rol_padre) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.frame = frame;
        this.rol_padre=rol_padre;
        if(rol_padre==0){
            cmbRol.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrarte = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(452, 320));
        setResizable(false);
        getContentPane().setLayout(null);

        btnRegistrarte.setText("Registrarte");
        btnRegistrarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarteActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarte);
        btnRegistrarte.setBounds(150, 234, 107, 23);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras);
        btnAtras.setBounds(20, 234, 107, 23);

        jLabel1.setText("Usuario :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(114, 57, 150, 31);

        jLabel2.setText("Password: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(91, 104, 190, 25);

        jLabel3.setText("Direccion de correo electronico: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 140, 160, 25);
        getContentPane().add(txtContrasenia);
        txtContrasenia.setBounds(184, 99, 202, 34);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(184, 57, 202, 31);
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(184, 140, 202, 29);

        jLabel4.setText("Introduzca los datos :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 25, 105, 14);

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Administrador" }));
        cmbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolActionPerformed(evt);
            }
        });
        getContentPane().add(cmbRol);
        cmbRol.setBounds(184, 180, 202, 20);

        jLabel5.setText("Rol Usuario :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(94, 183, 170, 14);

        jButton1.setText("Registar automatica");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(271, 234, 160, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract-background-design.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-6, 0, 460, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarteActionPerformed
       metodocrearusuarionormal();
    }//GEN-LAST:event_btnRegistrarteActionPerformed

    public boolean metodocrearusuarionormal(){
         // TODO add your handling code here:
         boolean usuariocreado=true;
         usuario = new Usuario(txtUsuario.getText(), txtContrasenia.getText(), txtCorreo.getText(),0,cmbRol.getSelectedIndex());

        final magesft.sockets.Sockets socket = new magesft.sockets.Sockets();
        final ObjectInputStream inputstream = socket.getIn();
        final ObjectOutputStream out = socket.getOut();
        final Socket stream = socket.getS();
        try {
            final String[] campos = {"Nombre_user", "Contrasenia", "Correo", "saldo", "rol"};

            final String recibido = (String) inputstream.readObject();
            System.out.println(recibido);

            out.writeObject(0);//opcion insertar
            out.writeObject("usuarios"); //tabla
            out.writeObject(campos);// campos sobre los que insertar
            final String[] v_insertar = {usuario.getUsuario(), usuario.getContrasenia(), usuario.getCorreo(), String.valueOf(usuario.getSaldo()), String.valueOf(usuario.getRol())};//valores a insertar
            out.writeObject(v_insertar);
            if(!(boolean)inputstream.readObject()){
                JOptionPane.showMessageDialog(this, "Comprueba los datos");
                usuariocreado=false;
                
            }
        } catch (IOException ex) {
            Logger.getLogger(CrearUsuario.class.getName()).log(Level.SEVERE, null, ex);
             usuariocreado=false;

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearUsuario.class.getName()).log(Level.SEVERE, null, ex);
             usuariocreado=false;
        } finally {
            try {
                out.flush();
                out.close();
                inputstream.close();
                stream.close();
            } catch (IOException ex) {
                Logger.getLogger(CrearUsuario.class.getName()).log(Level.SEVERE, null, ex);
                usuariocreado=false;
            }
        }
        return usuariocreado;
    }    
    
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
         frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed
    
    public boolean metodocrearautomatico(){
        boolean usuariocreado=true;
        int iden=0;
        final String tabla="usuarios";
        final String [] campo={"Nombre_user"};
        final String condicion="";
        Sockets socket=new Sockets();
        ObjectInputStream inputStream= socket.getIn();
        ObjectOutputStream out= socket.getOut();
        Socket stream=socket.getS();
        try {
            final String recibido = (String) inputStream.readObject();
            System.out.println(recibido);
            out.writeObject(1);
            out.writeObject(tabla);
            out.writeObject(campo);
            out.writeObject(condicion);
            iden =((ArrayList<String[]>)inputStream.readObject()).size();
            
        }catch(IOException | ClassNotFoundException ex){
           usuariocreado=false; 
        }
        
        
        
        usuario = new Usuario("MageSft"+iden, "MageSft"+iden, "MageSft"+iden+"@MageSft.com",0,cmbRol.getSelectedIndex());

        socket = new magesft.sockets.Sockets();
        inputStream = socket.getIn();
        out = socket.getOut();
        stream = socket.getS();
        try {
            final String[] campos = {"Nombre_user", "Contrasenia", "Correo", "saldo","rol"};

            final String recibido = (String) inputStream.readObject();
            System.out.println(recibido);

            out.writeObject(0);//opcion insertar
            out.writeObject("usuarios"); //tabla
            out.writeObject(campos);// campos sobre los que insertar
            final String[] v_insertar = {usuario.getUsuario(), usuario.getContrasenia(), usuario.getCorreo(), String.valueOf(usuario.getSaldo()), String.valueOf(usuario.getRol())};//valores a insertar
            out.writeObject(v_insertar);
            if(!(boolean)inputStream.readObject()){
                JOptionPane.showMessageDialog(this, "No se ha podido crear usuario");
                usuariocreado=true;
            }
        } catch (IOException ex) {
            Logger.getLogger(CrearUsuario.class.getName()).log(Level.SEVERE, null, ex);
            usuariocreado=true;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearUsuario.class.getName()).log(Level.SEVERE, null, ex);
            usuariocreado=true;
        } finally {
            try {
                out.flush();
                out.close();
                inputStream.close();
                stream.close();
            } catch (IOException ex) {
                Logger.getLogger(CrearUsuario.class.getName()).log(Level.SEVERE, null, ex);
                usuariocreado=true;
            }
        }
        return usuariocreado;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        metodocrearautomatico();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegistrarte;
    public javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField txtContrasenia;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    private Usuario usuario;
    JFrame frame;
    private Conexion_BBDD conexion;
}
