/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magesft.crearmusica;

import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import magesft.sockets.Sockets;

/**
 *
 * @author Gonzalo
 */
public class CrearAlbum extends javax.swing.JFrame {
DefaultListModel dfm;
    /**
     * Creates new form CrearAlbum
     */
    public CrearAlbum() {
        initComponents();
        dfm=new DefaultListModel<>();
        String tabla="album";
        String [] campo={"ID"};
        String condicion="";
        Sockets so=new Sockets();
        ObjectInputStream in= so.getIn();
        ObjectOutputStream out= so.getOut();
        Socket s=so.getS();
        try {
            String recibido = (String) in.readObject();
            System.out.println(recibido);
            out.writeObject(1);
            out.writeObject(tabla);
            out.writeObject(campo);
            out.writeObject(condicion);
            int iden=((ArrayList<String[]>)in.readObject()).size();
            l_iden.setText(String.valueOf(iden));
        }catch(Exception ex){
            l_iden.setText("0");
        }
        
        ArrayList autores;
        String tabla2="autor";
        String [] campo2={"Nombre"};
        String condicion2="";
        so=new Sockets();
        in= so.getIn();
        out= so.getOut();
        s=so.getS();
        try {
            String recibido = (String) in.readObject();
            System.out.println(recibido);
            out.writeObject(1);
            out.writeObject(tabla2);
            out.writeObject(campo2);
            out.writeObject(condicion2);
            autores=(ArrayList<String[]>)in.readObject();
            for (int i = 0; i < autores.size(); i++) {
                dfm.add(i, ((String)((String[])(autores.get(i)))[0]));
            }
            list_cancion.setModel(dfm);
            list_cancion.updateUI();
            if(autores.size()==0){
                JOptionPane.showMessageDialog(this, "No hay canciones");
                //IR ATRAS
            }
        }catch(Exception ex){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ist_canciones = new javax.swing.JScrollPane();
        list_cancion = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        l_iden = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        l_nombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ist_canciones.setViewportView(list_cancion);

        jLabel1.setText("ID:");

        l_iden.setEditable(false);

        jLabel2.setText("Nombre album:");

        jButton1.setText("Alta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_iden, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(91, 91, 91)))
                .addComponent(ist_canciones, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(l_iden, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(l_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(178, 178, 178)
                        .addComponent(jButton1))
                    .addComponent(ist_canciones, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String iden=l_iden.getText();
        String nombre=l_nombre.getText();
        String cancion=list_cancion.getSelectedValue();
        String tabla="album";
        String [] campos={"ID","Nombre_album","Autor"};
        String [] insertar={iden,nombre,cancion};
        if(list_cancion.getSelectedIndex()!=-1){
            Sockets so=new Sockets();
            ObjectInputStream in=so.getIn();
            ObjectOutputStream out=so.getOut();
            Socket s=so.getS();

            try{
                System.out.println(in.readObject());
                out.writeObject(0);
                out.writeObject(tabla);
                out.writeObject(campos);
                out.writeObject(insertar);
            }catch(Exception ex){

            }
        
            CrearAlbum c=new CrearAlbum();
            this.setVisible(false);
            c.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Selecciona un autor");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearAlbum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ist_canciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField l_iden;
    private javax.swing.JTextField l_nombre;
    private javax.swing.JList<String> list_cancion;
    // End of variables declaration//GEN-END:variables
}
