/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magesft.crearmusica;

import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import magesft.sockets.Sockets;
import magesft2.conectar.Conexion_BBDD;

/**
 *
 * @author Gonzalo
 */
public class CrearMusica extends javax.swing.JFrame {
    Conexion_BBDD co;
    DefaultListModel <String> dfm;
    /**
     * Creates new form CrearMusica
     */
    public CrearMusica() throws ClassNotFoundException, SQLException {
        initComponents();
        dfm=new DefaultListModel<>();
        String tabla="musica";
        String [] campo={"ID"};
        String condicion="";
        Sockets so=new Sockets();
        ObjectInputStream in= so.getIn();
        ObjectOutputStream out= so.getOut();
        Socket s=so.getS();
        try {
            String recibido = (String) in.readObject();
            System.out.println(recibido);
            out.writeObject(1);
            out.writeObject(tabla);
            out.writeObject(campo);
            out.writeObject(condicion);
            int iden=((ArrayList<String[]>)in.readObject()).size();
            t_id.setText(String.valueOf(iden));
        }catch(Exception ex){
            t_id.setText("0");
        }
        ArrayList autores;
        String tabla2="autor";
        String [] campo2={"Nombre"};
        String condicion2="";
        so=new Sockets();
        in= so.getIn();
        out= so.getOut();
        s=so.getS();
        try {
            String recibido = (String) in.readObject();
            System.out.println(recibido);
            out.writeObject(1);
            out.writeObject(tabla2);
            out.writeObject(campo2);
            out.writeObject(condicion2);
            autores=(ArrayList<String[]>)in.readObject();
            for (int i = 0; i < autores.size(); i++) {
                dfm.add(i, ((String)((String[])(autores.get(i)))[0]));
            }
            list_autores.setModel(dfm);
            list_autores.updateUI();
            if(autores.size()==0){
                JOptionPane.showMessageDialog(this, "No hay autores");
                //IR ATRAS
            }
        }catch(Exception ex){
            
        }
                
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        l_nombre = new javax.swing.JTextField();
        l_duracion = new javax.swing.JTextField();
        l_enlace = new javax.swing.JTextField();
        l_precio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_autores = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t_id.setEditable(false);

        jLabel1.setText("Identificador");

        jLabel2.setText("Insertar canciones:");

        jLabel3.setText("Nombre cancion:");

        jLabel4.setText("Duracion:");

        jLabel5.setText("Enlace:");

        jLabel6.setText("Precio:");

        jScrollPane1.setViewportView(list_autores);

        jButton1.setText("Alta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_enlace, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(jButton1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(l_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(l_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(l_enlace, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(l_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String iden=t_id.getText();
        String nombre=l_nombre.getText();
        String autor=list_autores.getSelectedValue();
        String duracion=l_duracion.getText();
        String enlace=l_enlace.getText();
        String precio=l_precio.getText();
        
        String tabla="musica";
        String [] campos={"Nombre_cancion","Autor","ID","Duracion","enlace","precio"};
        String [] insertar={nombre,autor,iden,duracion,enlace,precio};
        if(list_autores.getSelectedIndex()!=-1){
            Sockets so=new Sockets();
            ObjectInputStream in=so.getIn();
            ObjectOutputStream out=so.getOut();
            Socket s=so.getS();

            try{
                System.out.println(in.readObject());
                out.writeObject(0);
                out.writeObject(tabla);
                out.writeObject(campos);
                out.writeObject(insertar);
            }catch(Exception ex){

            }
        
            try {
                CrearMusica c=new CrearMusica();
                this.setVisible(false);
                c.setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CrearMusica.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CrearMusica.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Selecciona un autor");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CrearMusica().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CrearMusica.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(CrearMusica.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField l_duracion;
    private javax.swing.JTextField l_enlace;
    private javax.swing.JTextField l_nombre;
    private javax.swing.JTextField l_precio;
    private javax.swing.JList<String> list_autores;
    private javax.swing.JTextField t_id;
    // End of variables declaration//GEN-END:variables
}
