/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magesft.comprar;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import magesft.clases.Musica;
import magesft.clases.Usuario;
import magesft.reproductor.Panel;
import magesft.sockets.Sockets;

/**
 *
 * @author Gonzalo
 */
public class Comprar extends javax.swing.JFrame {

    DefaultListModel<Musica> dfm;
    LinkedList<Musica> l_musica;
    JFrame jf;
    Usuario u;

    /**
     * Creates new form BuscarCanciones
     */
    public Comprar(JFrame jf, Usuario u) {
        this.jf = jf;
        this.u = u;
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            dfm = new DefaultListModel<>();
            l_musica = new LinkedList<>();
            Sockets so = new Sockets();

            Socket s = so.getS();
            ObjectInputStream in = so.getIn();
            ObjectOutputStream out = so.getOut();

            System.out.println(in.readObject());
            String[] campos = {"Nombre"};
            String condicion = "";
            out.writeObject(1);
            out.writeObject("autor");
            out.writeObject(campos);
            out.writeObject(condicion);
            ArrayList<String[]> arr = (ArrayList<String[]>) in.readObject();

            for (int i = 0; i < arr.size(); i++) {
                c_artistas.addItem(((String[]) arr.get(i))[0]);
            }

            so = new Sockets();
            s = so.getS();
            in = so.getIn();
            out = so.getOut();

            System.out.println(in.readObject());
            String[] campos2 = {"ID", "Nombre_album"};
            out.writeObject(1);
            out.writeObject("album");
            out.writeObject(campos2);
            out.writeObject(condicion);
            arr = (ArrayList<String[]>) in.readObject();

            for (int i = 0; i < arr.size(); i++) {
                c_album.addItem(((String[]) arr.get(i))[0] + "-" + ((String[]) arr.get(i))[1]);
            }

        } catch (IOException ex) {
            Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        c_artistas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        c_album = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        l_titulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_musica = new javax.swing.JList<>();
        boton_comprar = new javax.swing.JButton();
        Btnatras = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(681, 415));
        setMinimumSize(new java.awt.Dimension(681, 415));
        setPreferredSize(new java.awt.Dimension(681, 415));
        getContentPane().setLayout(null);

        jLabel1.setText("Buscar canciones:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(432, 26, 190, 14);

        c_artistas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        getContentPane().add(c_artistas);
        c_artistas.setBounds(101, 64, 119, 20);

        jLabel2.setText("Artista:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(22, 67, 80, 14);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 360, 90, 23);

        jLabel3.setText("Album:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(22, 119, 80, 14);

        c_album.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        getContentPane().add(c_album);
        c_album.setBounds(101, 116, 119, 20);

        jLabel4.setText("Titulo: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(22, 175, 80, 14);
        getContentPane().add(l_titulo);
        l_titulo.setBounds(101, 172, 119, 20);

        jScrollPane1.setViewportView(list_musica);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(319, 64, 331, 307);

        boton_comprar.setText("Comprar");
        boton_comprar.setEnabled(false);
        boton_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_comprarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_comprar);
        boton_comprar.setBounds(200, 360, 90, 23);

        Btnatras.setText("Atrás");
        Btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnatrasActionPerformed(evt);
            }
        });
        getContentPane().add(Btnatras);
        Btnatras.setBounds(10, 360, 80, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract-background-design.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-6, 0, 690, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            l_musica = new LinkedList<>();
            dfm = new DefaultListModel<>();

            Sockets so = new Sockets();
            ArrayList<String[]> musica = new ArrayList<>();
            ObjectInputStream in = so.getIn();
            ObjectOutputStream out = so.getOut();

            String[] camp = {"Cancion"};

            System.out.println(in.readObject());
            out.writeObject(1);
            out.writeObject("usuariocancion");
            out.writeObject(camp);
            out.writeObject(" where Usuario='" + u.getUsuario() + "'");
            ArrayList<String[]> compradas = (ArrayList<String[]>) in.readObject();

            so = new Sockets();
            in = so.getIn();
            out = so.getOut();

            String artistas = (String) c_artistas.getSelectedItem();
            String album = (String) c_album.getSelectedItem();
            String nombre = l_titulo.getText();
            String cond_id = " ";
            for (int i = 0; i < compradas.size(); i++) {
                cond_id = cond_id + " and ID <>'" + ((String[]) compradas.get(i))[0] + "'";

            }
            if (nombre.compareToIgnoreCase("") != 0) {
                try {
                    String[] campos = {"Nombre_cancion", "Autor", "ID", "Duracion", "enlace", "Precio"};
                    String condicion = " where Nombre_cancion='" + nombre + "'" + cond_id;
                    System.out.println(in.readObject());
                    out.writeObject(1);
                    out.writeObject("musica");
                    out.writeObject(campos);
                    out.writeObject(condicion);
                    ArrayList<String[]> arr = (ArrayList<String[]>) in.readObject();
                    for (int i = 0; i < arr.size(); i++) {
                        musica.add(arr.get(i));
                    }

                } catch (IOException ex) {
                    Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                if (artistas.compareToIgnoreCase("") != 0) {

                    try {
                        String[] campos = {"Nombre_cancion", "Autor", "ID", "Duracion", "enlace", "Precio"};
                        String condicion = " where Autor='" + artistas + "'" + cond_id;
                        System.out.println(in.readObject());
                        out.writeObject(1);
                        out.writeObject("musica");
                        out.writeObject(campos);
                        out.writeObject(condicion);
                        ArrayList<String[]> arr = (ArrayList<String[]>) in.readObject();
                        for (int i = 0; i < arr.size(); i++) {
                            musica.add(arr.get(i));
                        }

                    } catch (IOException ex) {
                        Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    if (album.compareToIgnoreCase("") != 0) {
                        try {
                            String[] campos = {"ID_Musica"};
                            String condicion = " where ID_Album='" + album.substring(0, album.indexOf("-")) + "'";
                            System.out.println(in.readObject());
                            out.writeObject(1);
                            out.writeObject("linea_album");
                            out.writeObject(campos);
                            out.writeObject(condicion);
                            ArrayList<String[]> arr = (ArrayList<String[]>) in.readObject();

                            String[] campos2 = {"Nombre_cancion", "Autor", "ID", "Duracion", "enlace", "Precio"};
                            for (int i = 0; i < arr.size(); i++) {
                                so = new Sockets();

                                in = so.getIn();
                                out = so.getOut();
                                condicion = " where ID='" + ((String[]) arr.get(i))[0] + "'" + cond_id;
                                System.out.println(in.readObject());
                                out.writeObject(1);
                                out.writeObject("musica");
                                out.writeObject(campos2);
                                out.writeObject(condicion);
                                arr = (ArrayList<String[]>) in.readObject();
                                musica.add(arr.get(0));
                            }
                            for (int i = 0; i < musica.size(); i++) {
                                System.out.println(((String[]) musica.get(i))[0]);
                            }

                        } catch (IOException ex) {
                            Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Rellena alguno de los campos");
                    }

                }
            }
            for (int i = 0; i < musica.size(); i++) {
                String cancion = "";
                Musica m = new Musica(((String[]) musica.get(i))[0], ((String[]) musica.get(i))[1], ((String[]) musica.get(i))[2], ((String[]) musica.get(i))[3], ((String[]) musica.get(i))[4], ((String[]) musica.get(i))[5]);
                l_musica.add(m);
                dfm.add(i, m);
            }
            list_musica.setModel(dfm);
        } catch (IOException ex) {
            Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (l_musica.size() > 0) {
            boton_comprar.setEnabled(true);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void boton_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_comprarActionPerformed
        try {
            Sockets so = new Sockets();
            ObjectInputStream in = so.getIn();
            ObjectOutputStream out = so.getOut();

            String[] campos1 = {"saldo"};
            System.out.println(in.readObject());
            out.writeObject(1);
            out.writeObject("usuarios");
            out.writeObject(campos1);
            out.writeObject(" where Nombre_user='" + u.getUsuario() + "'");
            ArrayList<String[]> arr_saldo = (ArrayList<String[]>) in.readObject();
            float saldo = Float.parseFloat(((String[]) arr_saldo.get(0))[0]);
            float total_precio = 0;
            for (int i = 0; i < l_musica.size(); i++) {
                total_precio += Float.parseFloat(l_musica.get(i).getPrecio());
            }
            if (saldo >= total_precio) {
                for (int i = 0; i < l_musica.size(); i++) {
                    try {
                        // TODO add your handling code here:
                        so = new Sockets();
                        in = so.getIn();
                        out = so.getOut();

                        String[] campos2 = {"Usuario", "Cancion"};
                        String[] insertar = {u.getUsuario(), l_musica.get(i).getIden()};
                        String tabla = "usuariocancion";
                        System.out.println(in.readObject());
                        out.writeObject(0);
                        out.writeObject(tabla);
                        out.writeObject(campos2);
                        out.writeObject(insertar);

                    } catch (IOException ex) {
                        Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                so = new Sockets();
                in = so.getIn();
                out = so.getOut();

                String[] campos3 = {"saldo"};
                float s_ins = saldo - total_precio;
                String[] insertar_sal = {String.valueOf(s_ins)};

                System.out.println(in.readObject());
                out.writeObject(2);
                out.writeObject("usuarios");
                out.writeObject(campos3);
                out.writeObject(insertar_sal);
                out.writeObject(" Nombre_user='" + u.getUsuario() + "'");
                JOptionPane.showMessageDialog(this, "Compra realizada");
                jf.setVisible(true);
                this.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(this, "No tienes saldo suficiente");
            }
        } catch (IOException ex) {
            Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_boton_comprarActionPerformed

    private void BtnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnatrasActionPerformed
        jf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnatrasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnatras;
    private javax.swing.JButton boton_comprar;
    private javax.swing.JComboBox<String> c_album;
    private javax.swing.JComboBox<String> c_artistas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField l_titulo;
    private javax.swing.JList<Musica> list_musica;
    // End of variables declaration//GEN-END:variables
}
