/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magesft.loginusuario;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import magesft.clases.Usuario;
import magesft.sockets.Sockets;

/**
 *
 * @author Gonzalo
 */
public class LoginUsuario extends javax.swing.JFrame {
    JFrame frame;
    
    /**
     * Creates new form LoginUsuario
     */
    public LoginUsuario(final JFrame frame) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.frame=frame;
        this.setSize(fondo.getSize());

    }
    public LoginUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(fondo.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnAtras = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1325, 1024));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Introduzca sus credenciales y pulse Entrar para acceder a SoulMusic");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 327, 14);

        jLabel2.setText("Usuario :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(43, 46, 43, 14);

        jLabel3.setText("Contraseña :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(23, 84, 63, 14);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(130, 50, 209, 20);
        getContentPane().add(txtPass);
        txtPass.setBounds(130, 90, 209, 20);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras);
        btnAtras.setBounds(30, 150, 133, 41);

        btnEntrar.setText("Entrar");
        btnEntrar.setMaximumSize(new java.awt.Dimension(100, 100));
        btnEntrar.setMinimumSize(new java.awt.Dimension(100, 100));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(240, 150, 133, 39);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract-background-design.jpg"))); // NOI18N
        fondo.setText("jLabel4");
        fondo.setPreferredSize(new java.awt.Dimension(2000, 2000));
        getContentPane().add(fondo);
        fondo.setBounds(4, 0, 400, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        login();
    }//GEN-LAST:event_btnEntrarActionPerformed

    public boolean login(){
        // TODO add your handling code here:
        boolean usuariologueado=true;
        final Sockets socket = new Sockets();
        final ObjectInputStream inputStream = socket.getIn();
        final ObjectOutputStream out = socket.getOut();
        final Socket stream = socket.getS();
        final String[] campos = {"Nombre_user","Contrasenia","Correo","saldo","rol"};
        ArrayList<String[]> arr = null;
        Usuario usuario = null;
        try {
            final String recibido = (String) inputStream.readObject();
            System.out.println(recibido);
            out.writeObject(1);//Modelar en el servidor que cuando le pase 1 es consultas a BBDD
            out.writeObject("usuarios"); //tabla
            out.writeObject(campos);// campos sobre los que conusltar
            final String condicion = "WHERE Nombre_user = '" + txtUsuario.getText() + "' AND Contrasenia = '" + txtPass.getText() + "'";//Condicion
            out.writeObject(condicion);
            arr = (ArrayList<String[]>) inputStream.readObject();
            if (arr.size() == 1) {
                //siguiente ventana
                System.out.println("correcto");
                final String [] datos_u=arr.get(0);
                usuario=new Usuario(datos_u[0], datos_u[1], datos_u[2], Float.parseFloat(datos_u[3]), Integer.parseInt(datos_u[4]));
                final MenuUsuario menuprincipal=new MenuUsuario(this,usuario);
                menuprincipal.setVisible(true);
                this.setVisible(false);
            } else {
                usuariologueado=false;
                JOptionPane.showMessageDialog(this, "No existe el Usuario,\n intentelo de nuevo");
            }

        } catch (IOException ex) {
            Logger.getLogger(LoginUsuario.class.getName()).log(Level.SEVERE, null, ex);
             usuariologueado=false;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginUsuario.class.getName()).log(Level.SEVERE, null, ex);
             usuariologueado=false;
        } finally {
            try {
                out.flush();
                out.close();
                inputStream.close();
                stream.close();
                
                
                
            } catch (IOException ex) {
                Logger.getLogger(LoginUsuario.class.getName()).log(Level.SEVERE, null, ex);
                 usuariologueado=false;
            }
        }
        return usuariologueado;
    }
    
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        /*Inicio i = new Inicio(); //Importar desde el modulo crear usuario el JFrame Inicio
        i.setVisible(true);
        this.setVisible(false);*/
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPasswordField txtPass;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
