/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magesft.loginusuario;

import java.awt.BorderLayout;
import java.awt.LayoutManager;
import java.awt.Panel;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import magesft.buscarcanciones.BuscarCanciones;
import magesft.clases.Usuario;
import magesft.comprar.Comprar;
import magesft.reproductor.Reproductor;
import magesft.sockets.Sockets;
import magesft2.mensajes.Iniciosesiongmail;

/**
 *
 * @author ivan
 */
public class MenuUsuario extends javax.swing.JFrame {
    JFrame fp;
    Usuario u;
    /**
     * Creates new form MenuUsuario
     */
    public MenuUsuario() {
        initComponents();
    }
    
    public MenuUsuario(JFrame fp, Usuario u){
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.fp=fp;
        this.u=u;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntBEntrada = new javax.swing.JButton();
        btnReproductor = new javax.swing.JButton();
        Btneliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(775, 331));
        setMinimumSize(new java.awt.Dimension(775, 331));
        setPreferredSize(new java.awt.Dimension(775, 331));
        getContentPane().setLayout(null);

        bntBEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/002-send.png"))); // NOI18N
        bntBEntrada.setText("Buzon de Entrada");
        bntBEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(bntBEntrada);
        bntBEntrada.setBounds(50, 210, 200, 43);

        btnReproductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/003-video-player.png"))); // NOI18N
        btnReproductor.setText("Reproductor");
        btnReproductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproductorActionPerformed(evt);
            }
        });
        getContentPane().add(btnReproductor);
        btnReproductor.setBounds(400, 130, 200, 43);

        Btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/003-delete.png"))); // NOI18N
        Btneliminar.setText("Darse de baja");
        Btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Btneliminar);
        Btneliminar.setBounds(50, 130, 200, 43);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/004-add-song.png"))); // NOI18N
        jButton1.setText("Comprar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 210, 200, 43);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SoulMusic.JPG"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 10, 480, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract-background-design.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, 0, 780, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReproductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproductorActionPerformed
        BuscarCanciones c=new BuscarCanciones(this);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReproductorActionPerformed

    private void bntBEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBEntradaActionPerformed
        // TODO add your handling code here:
        Iniciosesiongmail gm=new Iniciosesiongmail(this);
        gm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntBEntradaActionPerformed

    private void BtneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtneliminarActionPerformed
        try {
            Sockets so=new Sockets();
            ObjectInputStream in=so.getIn();
            ObjectOutputStream out=so.getOut();
            System.out.println(in.readObject());
            out.writeObject(3);
            out.writeObject("usuariocancion");
            out.writeObject("Usuario='"+u.getUsuario()+"'");
            
            
            
            so=new Sockets();
            in=so.getIn();
            out=so.getOut();
            
            System.out.println(in.readObject());
            out.writeObject(3);
            out.writeObject("usuarios");
            out.writeObject("Nombre_user='"+u.getUsuario()+"'");
            fp.setVisible(true);
            this.setVisible(false);
            
        } catch (IOException ex) {
            Logger.getLogger(MenuUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtneliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Comprar comp=new Comprar(this, u);
        comp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btneliminar;
    private javax.swing.JButton bntBEntrada;
    private javax.swing.JButton btnReproductor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
