/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magesft2.crearusuario;

import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import jdk.net.Sockets;
import magesft.clases.Usuario;
import magesft2.conectar.Conexion_BBDD;

/**
 *
 * @author ivan
 */
public class CrearUsuario extends javax.swing.JFrame {
int rol_padre;
    /**
     * Creates new form CrearUsuario
     */
    public CrearUsuario() {
        initComponents();
    }
    public CrearUsuario(JFrame fr, int rol_padre) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.fr = fr;
        this.rol_padre=rol_padre;
        if(rol_padre==0){
            cmbRol.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrarte = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 340));
        setMinimumSize(new java.awt.Dimension(450, 340));
        setPreferredSize(new java.awt.Dimension(450, 340));
        getContentPane().setLayout(null);

        btnRegistrarte.setText("Registrarte");
        btnRegistrarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarteActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarte);
        btnRegistrarte.setBounds(140, 248, 107, 23);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras);
        btnAtras.setBounds(10, 248, 107, 23);

        jLabel1.setText("Usuario :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(104, 63, 60, 31);

        jLabel2.setText("Contraseña :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(81, 110, 83, 25);

        jLabel3.setText("Direccion de correo electronico: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 145, 154, 25);
        getContentPane().add(txtContraseña);
        txtContraseña.setBounds(174, 105, 202, 34);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(174, 63, 202, 31);
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(174, 146, 202, 29);

        jLabel4.setText("Introduzca los datos :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 31, 105, 14);

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Administrador" }));
        getContentPane().add(cmbRol);
        cmbRol.setBounds(174, 186, 202, 20);

        jLabel5.setText("Rol Usuario :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(84, 189, 61, 14);

        jButton1.setText("Registar automatica");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 250, 160, 23);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(256, 289, 0, 0);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract-background-design.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-25, -9, 480, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarteActionPerformed
        // TODO add your handling code here:
        
        u = new Usuario(txtUsuario.getText(), txtContraseña.getText(), txtCorreo.getText(), cmbRol.getSelectedIndex());
        try { 
            String rol = String.valueOf(u.getRol());
            c = new Conexion_BBDD();
            String[] campos = {"Nombre_user", "Contrasenia", "Correo", "saldo","rol"};
            String[] v_insertar = {u.getUsuario(), u.getContrasenia(), u.getCorreo(), String.valueOf(u.getSaldo()), rol};
            c.insertar("usuarios", campos, v_insertar);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CrearUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarteActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        fr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {                                         
            int iden=0;
            try {
                
                String tabla="usuarios";
                String [] campo={"Nombre_user"};
                String condicion="";
                Conexion_BBDD c=new Conexion_BBDD();
                iden =((ArrayList<String[]>) c.consulta(tabla, campo, condicion)).size();
                
            }catch(Exception ex){
                
            }
            
            
            
            Usuario u = new Usuario("MageSft"+iden, "MageSft"+iden, "MageSft"+iden+"@MageSft.com",0,cmbRol.getSelectedIndex());
            
            Conexion_BBDD c2=new Conexion_BBDD();
            
            String[] campos = {"Nombre_user", "Contrasenia", "Correo", "saldo", "rol"};
            String[] v_insertar = {u.getUsuario(), u.getContrasenia(), u.getCorreo(), String.valueOf(u.getSaldo()),String.valueOf(u.getRol())};//valores a insertar
            c2.insertar("usuarios", campos, v_insertar);
            
            
            
            
        }catch(ClassNotFoundException ex){
        Logger.getLogger(CrearUsuario.class.getName()).log(Level.SEVERE, null, ex);
            
        } catch (SQLException ex) {
        Logger.getLogger(CrearUsuario.class.getName()).log(Level.SEVERE, null, ex);
    }
    
            
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegistrarte;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    private Usuario u;
    JFrame fr;
    private Conexion_BBDD c;
}
