/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magesft.crearmusica;

import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import magesft.sockets.Sockets;
import magesft2.conectar.Conexion_BBDD;

/**
 *
 * @author Gonzalo
 */
public class CrearMusica extends javax.swing.JFrame {
    Conexion_BBDD co;
    DefaultListModel <String> dfm;
    JFrame jf;
    /**
     * Creates new form CrearMusica
     */
    public CrearMusica(JFrame jf) throws ClassNotFoundException, SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jf=jf;
        dfm=new DefaultListModel<>();
        String tabla="musica";
        String [] campo={"ID"};
        String condicion="";
        Sockets so=new Sockets();
        ObjectInputStream in= so.getIn();
        ObjectOutputStream out= so.getOut();
        Socket s=so.getS();
        try {
            String recibido = (String) in.readObject();
            System.out.println(recibido);
            out.writeObject(1);
            out.writeObject(tabla);
            out.writeObject(campo);
            out.writeObject(condicion);
            int iden=((ArrayList<String[]>)in.readObject()).size();
            t_id.setText(String.valueOf(iden));
        }catch(Exception ex){
            t_id.setText("0");
        }
        ArrayList autores;
        String tabla2="autor";
        String [] campo2={"Nombre"};
        String condicion2="";
        so=new Sockets();
        in= so.getIn();
        out= so.getOut();
        s=so.getS();
        try {
            String recibido = (String) in.readObject();
            System.out.println(recibido);
            out.writeObject(1);
            out.writeObject(tabla2);
            out.writeObject(campo2);
            out.writeObject(condicion2);
            autores=(ArrayList<String[]>)in.readObject();
            for (int i = 0; i < autores.size(); i++) {
                dfm.add(i, ((String)((String[])(autores.get(i)))[0]));
            }
            list_autores.setModel(dfm);
            list_autores.updateUI();
            if(autores.size()==0){
                JOptionPane.showMessageDialog(this, "No hay autores");
                //IR ATRAS
            }
        }catch(Exception ex){
            
        }
                
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        l_nombre = new javax.swing.JTextField();
        l_duracion = new javax.swing.JTextField();
        l_enlace = new javax.swing.JTextField();
        l_precio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_autores = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        Btnatras = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(830, 430));
        setMinimumSize(new java.awt.Dimension(830, 430));
        setPreferredSize(new java.awt.Dimension(830, 430));
        getContentPane().setLayout(null);

        t_id.setEditable(false);
        getContentPane().add(t_id);
        t_id.setBounds(186, 50, 53, 33);

        jLabel1.setText("Identificador");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(43, 59, 120, 14);

        jLabel2.setText("Insertar canciones:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(134, 18, 200, 14);

        jLabel3.setText("Nombre cancion:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(43, 118, 120, 14);

        jLabel4.setText("Duracion:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(43, 178, 130, 14);

        jLabel5.setText("Enlace:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(43, 237, 130, 14);

        jLabel6.setText("Precio:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(45, 283, 120, 14);
        getContentPane().add(l_nombre);
        l_nombre.setBounds(180, 110, 146, 33);
        getContentPane().add(l_duracion);
        l_duracion.setBounds(186, 169, 52, 33);
        getContentPane().add(l_enlace);
        l_enlace.setBounds(186, 229, 201, 30);
        getContentPane().add(l_precio);
        l_precio.setBounds(186, 273, 58, 34);

        jScrollPane1.setViewportView(list_autores);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(505, 50, 281, 257);

        jButton1.setText("Alta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 323, 51, 23);

        Btnatras.setText("Atrás");
        Btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnatrasActionPerformed(evt);
            }
        });
        getContentPane().add(Btnatras);
        Btnatras.setBounds(593, 323, 59, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract-background-design.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(4, -2, 830, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String iden=t_id.getText();
        String nombre=l_nombre.getText();
        String autor=list_autores.getSelectedValue();
        String duracion=l_duracion.getText();
        String enlace=l_enlace.getText();
        String precio=l_precio.getText();
        
        
        String tabla="musica";
        String [] campos={"Nombre_cancion","Autor","ID","Duracion","enlace","precio"};
        String [] insertar={nombre,autor,iden,duracion,enlace,precio};
        if(list_autores.getSelectedIndex()!=-1){
            Sockets so=new Sockets();
            ObjectInputStream in=so.getIn();
            ObjectOutputStream out=so.getOut();
            Socket s=so.getS();

            try{
                System.out.println(in.readObject());
                out.writeObject(0);
                out.writeObject(tabla);
                out.writeObject(campos);
                out.writeObject(insertar);
            }catch(Exception ex){

            }
        
            try {
                CrearMusica c=new CrearMusica(jf);
                this.setVisible(false);
                c.setVisible(true);
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CrearMusica.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CrearMusica.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Selecciona un autor");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnatrasActionPerformed
        jf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnatrasActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnatras;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField l_duracion;
    private javax.swing.JTextField l_enlace;
    private javax.swing.JTextField l_nombre;
    private javax.swing.JTextField l_precio;
    private javax.swing.JList<String> list_autores;
    private javax.swing.JTextField t_id;
    // End of variables declaration//GEN-END:variables
}
